name: Generate Stats Images

on:
  schedule:
    - cron: "0 0 * * *" # Runs at midnight every day
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate-images:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: jstrieb/github-stats@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
